target("CoreTest")
    set_kind("binary")
    set_group("Test")
    add_files("**.cpp")
    add_headerfiles("**.hpp")
    add_deps("Core")
    add_packages("gtest", {public = true})
    add_includedirs("$(projectdir)/test/core_test", {public = true})
target_end()