target("App")
    set_kind("binary")
    set_group("Engine")
    add_files("**.cpp")
    add_headerfiles("**.hpp")
    add_deps("Core", "Render")
    add_includedirs("$(projectdir)/source/app")
target_end()