target("App")
    set_kind("binary")
    set_group("Engine")
    add_files("**.cpp")
    add_headerfiles("**.hpp")
    add_deps("Core", "Render")
    add_includedirs("$(projectdir)/source/app")

    -- local glfw_path = os.getenv("GLFW")
    -- add_includedirs(glfw_path .. "/include", {public = true})
    -- add_linkdirs(glfw_path .. "/lib-vc2019")
    -- add_links("glfw3")
    add_packages("glfw")
target_end()