#pragma once

#include <stdint.h>
#include <shared_mutex>
#include <filesystem>
#include <initializer_list>
#include <algorithm>
#include <atomic>
#include <functional>
#include <tuple>
#include <queue>
#include <memory>
#include <optional>
#include <chrono>
#include <type_traits>
#include <exception>
#include <cstdlib>
#include <utility>
#include <bit>
#include <cmath>
#include <span>
#include <new>
#include <xmemory>
#include <thread>
#include <condition_variable>
#include <future>
#include <cstring>
#include <fstream>